version: '3'
services:
  app:
    build:
      context: app
    command: npm run serve
    environment:
      PORT: '8080'
      HOST: '0.0.0.0'
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - ./app:/app/src
